name: CI

on: 
  pull_request:
    types: [opened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Dreamcodeio/pr-has-label-action@master
      with:
        label: PROVISION:FEATURE_BRANCH


