name: CI

on: 
  pull_request:
    types: [opened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkLabel
      with:
        label: PROVISION:FEATURE_BRANCH
    - name: Does 'pull_request' has ${{ steps.checkLabel.outputs.checkedLabel }} label? 
      run: echo "${{ steps.checkLabel.outputs.hasLabel }}" 
    - uses: Dreamcodeio/whats-the-pr-branch@master
      id: branchName
      with:
        prefix: feature/,hotfix/
    - name: What's the PR branch name? 
      run: echo "${{ steps.branchName.outputs.branchName }}" 
