name: CI

on: 
  pull_request:
    types: [opened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Dreamcodeio/pr-has-label-action@master
      with:
        label: PROVISION:FEATURE_BRANCH
    - name: Does 'pull_request' has ${{ steps.hello.outputs.checkedLabel }} label? 
      run: echo ${{ steps.hello.outputs.hasLabel }}" 
